algoritmo "Contador"
var
   valor , contador : inteiro

inicio
   contador <-0
   escreva (" Até que número você quer contar? ")
   Leia (valor)
   Enquanto (contador <= valor) faca
    escreval (" -----------------------")
    escreval (contador)
    escreval (" -----------------------")
     contador <- contador + 1
   fimenquanto
    escreval (" -----------------------")
    escreval (" Terminei de contar !!! ")
    escreval (" -----------------------")

fimalgoritmo